### ISSUE TITLE
Converting landmark data format

### ISSUE THREAD

**Issue by hshreeshail** [TesseraktZero/UnityHandTrackingWithMediapipe#15]
MediaPipe gives output data in the form of (x,y,z) co-ordinates (normalized and adjusted wrt origin etc). When animating a Unity avatar, does this data have to be converted to 3D rotation data (ex: Quaternion format) for the joints?

**Comment by TesseraktZero** [comment]
The 3d position data are being used as position targets for the IK system (animation rigging package).
