### ISSUE TITLE
Where can I can find the UnityHandTracking.apk?

### ISSUE THREAD

**Issue by wangtss** [TesseraktZero/UnityHandTrackingWithMediapipe#3]
Sorry for the silly question, but I can't find the UnityHandTracking.apk.....

**Comment by TesseraktZero** [comment]
https://github.com/TesseraktZero/UnityHandTrackingWithMediapipe/releases

Click on the "Assets" label and you will see the apk

**Comment by wangtss** [comment]
Great!!
